title: pizzodev
description: Publications and writings
url: "https://pizzodev.github.io"
baseurl: ""

collections:
  publications:
    output: true
    permalink: /:collection/:name/

# Build settings
theme: null
plugins: []

exclude:
  - README.md
  - .DS_Store
